### PR TITLE
Add filter to be able to modify shipment query

### PR DESCRIPTION
**Pull request by maxsakal**
Hello! Please review my code and let me know if there are any required changes to this :)

### CODE REVIEW

**Comment by dennisnissle** [comment]
Hi! Thank you for your pull request. Could you elaborate a little on what you are trying to do/achieve with this filter? This filter may only be used with great caution as the filtered result will be passed without any escaping to `$wpdb` - this is why I think it needs a little more context.

**Comment by maxsakal** [comment]
@dennisnissle Thanks for the review, sure! I want to implement shipment filtering by product. For this, I need to modify the query and join the shipment_items table.
I've added this filter in the same way as WP_Query has. I agree that all passed data should be escaped, but this responsibility is on the developer that uses this filter.

**Comment by dennisnissle** [comment]
@maxsakal Do you want to filter by product id? I guess it would be more developer/extendibility-friendly to introduce a new query_var (e.g. `product_ids`) in [ShipmentQuery](https://github.com/vendidero/woocommerce-germanized-shipments/blob/master/src/ShipmentQuery.php#L49) and then add the logic (where + joins) to the `prepare_query()` method. What do you think?

**Comment by maxsakal** [comment]
@dennisnissle I was thinking about it, but we are working a lot with shipments and it would be great to be able to modify query without modifying the plugin each time for our needs.

**Comment by dennisnissle** [comment]
The problem with adjusting the query (SQL) directly is that it may lead to errors in the future/updates as soon as the db schema changes. That's why some sort of abstraction is very much appreciated. I think the product_id filtering is a great extension for a query_var - could you change your code accordingly? We can add the very generic filter to manipulate the actual query too for more specific purposes.

**Comment by maxsakal** [comment]
Okay, thanks, I will make and commit changes 👌

**Comment by maxsakal** [comment]
@dennisnissle Done and tested ✅
https://github.com/vendidero/woocommerce-germanized-shipments/pull/15/commits/d226cd56de4e99636cc297de18604f2274b074bd

**Comment by dennisnissle** [comment]
Nice, thanks! Merged :)

**Pull request merged**
