### PR TITLE
Added filter for shipment query clauses

### PR DESCRIPTION
**Pull request by migueldamota**
Hello, with this update I want to achieve that you will be able to add custom where, join clauses to the shipment query.

For example, we want to filter shipments by their invoices based on their order, to achieve this we had to add a custom query. That's why I want to update this. I already used this code locally and it works fine 👍

If you have any questions or if there are any required changes let me know 😄

### CODE REVIEW

**Comment by dennisnissle** [comment]
Hi @migueldamota,

thank you for your pull request. We've already had a discussion on the very same topic [here](https://github.com/vendidero/woocommerce-germanized-shipments/pull/15). To filter shipments by their order you might just use the `order_id` param?

Best,
Dennis

**Comment by migueldamota** [comment]
Hi @dennisnissle.

thanks for the quick response. I meant that we want to filter shipments by the invoice number which is connected to the shipment order. So we search the invoice number and it will show all shipments by an order by the invoice number. To use the invoice numbers we have Germanized Pro but we can't filter by that since we can't update the query clauses. Sorry that I didn't explain it properly.

**Comment by dennisnissle** [comment]
Invoices (in Germanized Pro) are not created to shipments but to orders - shipments are not part of invoices. Only packing slips are created for shipments directly that's why I'm not quire aware of the actual use-case here. Did you check the arguments mentioned from the pull request linked in my last response?

**Comment by migueldamota** [comment]
Exactly, invoices are only created for orders and not for shipments. However, sometimes a customer calls and only has the invoice number available. To quickly be able to check the shipment status for the customer in such a case, it would be great, to be able to search for the invoice number.
I get the point from the other PR, however in this case, it doesn't make sense to add a specific filter because not everybody has Germanized Pro, right? 
I also saw in the other PR, that you said:
> We can add the very generic filter to manipulate the actual query too for more specific purposes.

Or does that mean, that we can actually create the generic filter? 
Or do you have any other ideas, or approaches, on how to do this the best way possible?

**Comment by dennisnissle** [comment]
> To quickly be able to check the shipment status for the customer in such a case, it would be great, to be able to search for the invoice number.

You might just search the orders (WooCommerce > Orders) for the invoice number. The shipping status is registered as a custom column in the table.

Anyway, I've just added a generic filter based on the [original approach](https://github.com/vendidero/woocommerce-germanized-shipments/pull/15/commits/6b6dcfa62aae4cf8dbd99135afdfeca6fd72ea2a) (from the original PR) as it was a little more fine-tuned. Please see: https://github.com/vendidero/woocommerce-germanized-shipments/commit/314ff1617aee67e50a9f1966e3145d2b0ffbdf68

Cheers

**Comment by migueldamota** [comment]
All right, thank you for your time 👍

**Comment by dennisnissle** [comment]
Glad to help, thank you for your contribution :)

Best,
Dennis

**Pull request closed without merging**
